package com.google.android.gms.internal.ads;

import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import android.text.TextUtils;
import com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable;
import com.google.android.gms.common.internal.safeparcel.SafeParcelWriter;
import java.util.Collections;
import java.util.List;
import javax.annotation.ParametersAreNonnullByDefault;

@ParametersAreNonnullByDefault
/* compiled from: com.google.android.gms:play-services-ads@@19.4.0 */
public final class zzasp extends AbstractSafeParcelable {
    public static final Parcelable.Creator<zzasp> CREATOR = new zzaso();
    private final int errorCode;
    private final int orientation;
    private final int versionCode;
    private final zzasr zzboh;
    private final boolean zzbpc;
    private final boolean zzbpd;
    private final boolean zzbrg;
    private final boolean zzchv;
    private final boolean zzchw;
    private final List<String> zzdkj;
    private final List<String> zzdkk;
    private final List<String> zzdkl;
    private final List<String> zzdkn;
    private final boolean zzdko;
    private final long zzdkq;
    private final String zzdpn;
    private final boolean zzdqy;
    private final boolean zzdrl;
    private String zzdrm;
    private final boolean zzdry;
    private String zzdsl;
    private final long zzdsm;
    private final boolean zzdsn;
    private final long zzdso;
    private final List<String> zzdsp;
    private final String zzdsq;
    private final long zzdsr;
    private final String zzdss;
    private final boolean zzdst;
    private final String zzdsu;
    private final String zzdsv;
    private final boolean zzdsw;
    private final boolean zzdsx;
    private final boolean zzdsy;
    private zzatb zzdsz;
    private String zzdta;
    private final String zzdtb;
    private final zzauv zzdtc;
    private final List<String> zzdtd;
    private final List<String> zzdte;
    private final boolean zzdtf;
    private final String zzdtg;
    private final zzawg zzdth;
    private final String zzdti;
    private final boolean zzdtj;
    private Bundle zzdtk;
    private final int zzdtl;
    private final boolean zzdtm;
    private final String zzdtn;
    private String zzdto;
    private boolean zzdtp;
    private boolean zzdtq;

    zzasp(int i, String str, String str2, List<String> list, int i2, List<String> list2, long j, boolean z, long j2, List<String> list3, long j3, int i3, String str3, long j4, String str4, boolean z2, String str5, String str6, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, zzatb zzatb, String str7, String str8, boolean z8, boolean z9, zzauv zzauv, List<String> list4, List<String> list5, boolean z10, zzasr zzasr, boolean z11, String str9, List<String> list6, boolean z12, String str10, zzawg zzawg, String str11, boolean z13, boolean z14, Bundle bundle, boolean z15, int i4, boolean z16, List<String> list7, boolean z17, String str12, String str13, boolean z18, boolean z19) {
        zzate zzate;
        zzatb zzatb2 = zzatb;
        this.versionCode = i;
        this.zzdpn = str;
        this.zzdsl = str2;
        List<String> list8 = null;
        this.zzdkj = list != null ? Collections.unmodifiableList(list) : null;
        this.errorCode = i2;
        this.zzdkk = list2 != null ? Collections.unmodifiableList(list2) : null;
        this.zzdsm = j;
        this.zzdsn = z;
        this.zzdso = j2;
        this.zzdsp = list3 != null ? Collections.unmodifiableList(list3) : null;
        this.zzdkq = j3;
        this.orientation = i3;
        this.zzdsq = str3;
        this.zzdsr = j4;
        this.zzdss = str4;
        this.zzdst = z2;
        this.zzdsu = str5;
        this.zzdsv = str6;
        this.zzdsw = z3;
        this.zzbrg = z4;
        this.zzdqy = z5;
        this.zzdsx = z6;
        this.zzdtj = z13;
        this.zzdsy = z7;
        this.zzdsz = zzatb2;
        this.zzdta = str7;
        this.zzdtb = str8;
        if (this.zzdsl == null && zzatb2 != null && (zzate = (zzate) zzatb2.zza(zzate.CREATOR)) != null && !TextUtils.isEmpty(zzate.zzdud)) {
            this.zzdsl = zzate.zzdud;
        }
        this.zzchv = z8;
        this.zzchw = z9;
        this.zzdtc = zzauv;
        this.zzdtd = list4;
        this.zzdte = list5;
        this.zzdtf = z10;
        this.zzboh = zzasr;
        this.zzdrl = z11;
        this.zzdrm = str9;
        this.zzdkn = list6;
        this.zzdko = z12;
        this.zzdtg = str10;
        this.zzdth = zzawg;
        this.zzdti = str11;
        this.zzdry = z14;
        this.zzdtk = bundle;
        this.zzbpc = z15;
        this.zzdtl = i4;
        this.zzdtm = z16;
        this.zzdkl = list7 != null ? Collections.unmodifiableList(list7) : list8;
        this.zzbpd = z17;
        this.zzdtn = str12;
        this.zzdto = str13;
        this.zzdtp = z18;
        this.zzdtq = z19;
    }

    public final void writeToParcel(Parcel parcel, int i) {
        int beginObjectHeader = SafeParcelWriter.beginObjectHeader(parcel);
        SafeParcelWriter.writeInt(parcel, 1, this.versionCode);
        SafeParcelWriter.writeString(parcel, 2, this.zzdpn, false);
        SafeParcelWriter.writeString(parcel, 3, this.zzdsl, false);
        SafeParcelWriter.writeStringList(parcel, 4, this.zzdkj, false);
        SafeParcelWriter.writeInt(parcel, 5, this.errorCode);
        SafeParcelWriter.writeStringList(parcel, 6, this.zzdkk, false);
        SafeParcelWriter.writeLong(parcel, 7, this.zzdsm);
        SafeParcelWriter.writeBoolean(parcel, 8, this.zzdsn);
        SafeParcelWriter.writeLong(parcel, 9, this.zzdso);
        SafeParcelWriter.writeStringList(parcel, 10, this.zzdsp, false);
        SafeParcelWriter.writeLong(parcel, 11, this.zzdkq);
        SafeParcelWriter.writeInt(parcel, 12, this.orientation);
        SafeParcelWriter.writeString(parcel, 13, this.zzdsq, false);
        SafeParcelWriter.writeLong(parcel, 14, this.zzdsr);
        SafeParcelWriter.writeString(parcel, 15, this.zzdss, false);
        SafeParcelWriter.writeBoolean(parcel, 18, this.zzdst);
        SafeParcelWriter.writeString(parcel, 19, this.zzdsu, false);
        SafeParcelWriter.writeString(parcel, 21, this.zzdsv, false);
        SafeParcelWriter.writeBoolean(parcel, 22, this.zzdsw);
        SafeParcelWriter.writeBoolean(parcel, 23, this.zzbrg);
        SafeParcelWriter.writeBoolean(parcel, 24, this.zzdqy);
        SafeParcelWriter.writeBoolean(parcel, 25, this.zzdsx);
        SafeParcelWriter.writeBoolean(parcel, 26, this.zzdsy);
        SafeParcelWriter.writeParcelable(parcel, 28, this.zzdsz, i, false);
        SafeParcelWriter.writeString(parcel, 29, this.zzdta, false);
        SafeParcelWriter.writeString(parcel, 30, this.zzdtb, false);
        SafeParcelWriter.writeBoolean(parcel, 31, this.zzchv);
        SafeParcelWriter.writeBoolean(parcel, 32, this.zzchw);
        SafeParcelWriter.writeParcelable(parcel, 33, this.zzdtc, i, false);
        SafeParcelWriter.writeStringList(parcel, 34, this.zzdtd, false);
        SafeParcelWriter.writeStringList(parcel, 35, this.zzdte, false);
        SafeParcelWriter.writeBoolean(parcel, 36, this.zzdtf);
        SafeParcelWriter.writeParcelable(parcel, 37, this.zzboh, i, false);
        SafeParcelWriter.writeBoolean(parcel, 38, this.zzdrl);
        SafeParcelWriter.writeString(parcel, 39, this.zzdrm, false);
        SafeParcelWriter.writeStringList(parcel, 40, this.zzdkn, false);
        SafeParcelWriter.writeBoolean(parcel, 42, this.zzdko);
        SafeParcelWriter.writeString(parcel, 43, this.zzdtg, false);
        SafeParcelWriter.writeParcelable(parcel, 44, this.zzdth, i, false);
        SafeParcelWriter.writeString(parcel, 45, this.zzdti, false);
        SafeParcelWriter.writeBoolean(parcel, 46, this.zzdtj);
        SafeParcelWriter.writeBoolean(parcel, 47, this.zzdry);
        SafeParcelWriter.writeBundle(parcel, 48, this.zzdtk, false);
        SafeParcelWriter.writeBoolean(parcel, 49, this.zzbpc);
        SafeParcelWriter.writeInt(parcel, 50, this.zzdtl);
        SafeParcelWriter.writeBoolean(parcel, 51, this.zzdtm);
        SafeParcelWriter.writeStringList(parcel, 52, this.zzdkl, false);
        SafeParcelWriter.writeBoolean(parcel, 53, this.zzbpd);
        SafeParcelWriter.writeString(parcel, 54, this.zzdtn, false);
        SafeParcelWriter.writeString(parcel, 55, this.zzdto, false);
        SafeParcelWriter.writeBoolean(parcel, 56, this.zzdtp);
        SafeParcelWriter.writeBoolean(parcel, 57, this.zzdtq);
        SafeParcelWriter.finishObjectHeader(parcel, beginObjectHeader);
    }
}
