package expo.modules.imagepicker;

import androidx.exifinterface.media.ExifInterface;
import com.google.android.exoplayer2.extractor.p012ts.TsExtractor;
import kotlin.Metadata;

@Metadata(mo40251bv = {1, 0, 3}, mo40252d1 = {"\u0000$\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0002\n\u0002\u0010\u000e\n\u0002\b\u0005\n\u0002\u0010\b\n\u0002\b\u0015\n\u0002\u0010\u0011\n\u0002\b\u0004\bÆ\u0002\u0018\u00002\u00020\u0001B\u0007\b\u0002¢\u0006\u0002\u0010\u0002R\u000e\u0010\u0003\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\u0005\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\u0006\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\u0007\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\b\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\t\u001a\u00020\nXT¢\u0006\u0002\n\u0000R\u000e\u0010\u000b\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\f\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\r\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\u000e\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\u000f\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\u0010\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\u0011\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\u0012\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\u0013\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\u0014\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\u0015\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\u0016\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\u0017\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\u0018\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\u0019\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\u001a\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\u001b\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u000e\u0010\u001c\u001a\u00020\nXT¢\u0006\u0002\n\u0000R\u000e\u0010\u001d\u001a\u00020\nXT¢\u0006\u0002\n\u0000R\u000e\u0010\u001e\u001a\u00020\u0004XT¢\u0006\u0002\n\u0000R\u001f\u0010\u001f\u001a\u000e\u0012\n\u0012\b\u0012\u0004\u0012\u00020\u00040 0 ¢\u0006\n\n\u0002\u0010#\u001a\u0004\b!\u0010\"¨\u0006$"}, mo40253d2 = {"Lexpo/modules/imagepicker/ImagePickerConstants;", "", "()V", "CACHE_DIR_NAME", "", "CAN_NOT_DEDUCE_TYPE_MESSAGE", "CAN_NOT_EXTRACT_METADATA_MESSAGE", "CAN_NOT_OPEN_CROP_MESSAGE", "CAN_NOT_SAVE_RESULT_MESSAGE", "DEFAULT_QUALITY", "", "ERR_CAN_NOT_DEDUCE_TYPE", "ERR_CAN_NOT_EXTRACT_METADATA", "ERR_CAN_NOT_OPEN_CROP", "ERR_CAN_NOT_SAVE_RESULT", "ERR_INVALID_OPTION", "ERR_MISSING_ACTIVITY", "ERR_MISSING_URL", "MISSING_ACTIVITY_MESSAGE", "MISSING_URL_MESSAGE", "OPTION_ALLOWS_EDITING", "OPTION_ASPECT", "OPTION_BASE64", "OPTION_EXIF", "OPTION_MEDIA_TYPES", "OPTION_QUALITY", "OPTION_VIDEO_MAX_DURATION", "PENDING_RESULT_EVENT", "REQUEST_LAUNCH_CAMERA", "REQUEST_LAUNCH_IMAGE_LIBRARY", "TAG", "exifTags", "", "getExifTags", "()[[Ljava/lang/String;", "[[Ljava/lang/String;", "expo-image-picker_release"}, mo40254k = 1, mo40255mv = {1, 4, 2})
/* compiled from: ImagePickerConstants.kt */
public final class ImagePickerConstants {
    public static final String CACHE_DIR_NAME = "ImagePicker";
    public static final String CAN_NOT_DEDUCE_TYPE_MESSAGE = "Can not deduce type of the returned file.";
    public static final String CAN_NOT_EXTRACT_METADATA_MESSAGE = "Can not extract metadata.";
    public static final String CAN_NOT_OPEN_CROP_MESSAGE = "Can not open the crop tool.";
    public static final String CAN_NOT_SAVE_RESULT_MESSAGE = "Can not save result to the file.";
    public static final int DEFAULT_QUALITY = 100;
    public static final String ERR_CAN_NOT_DEDUCE_TYPE = "ERR_CAN_NOT_DEDUCE_TYPE";
    public static final String ERR_CAN_NOT_EXTRACT_METADATA = "ERR_CAN_NOT_EXTRACT_METADATA";
    public static final String ERR_CAN_NOT_OPEN_CROP = "ERR_CAN_NOT_OPEN_CROP";
    public static final String ERR_CAN_NOT_SAVE_RESULT = "ERR_CAN_NOT_SAVE_RESULT";
    public static final String ERR_INVALID_OPTION = "ERR_INVALID_OPTION";
    public static final String ERR_MISSING_ACTIVITY = "ERR_MISSING_ACTIVITY";
    public static final String ERR_MISSING_URL = "ERR_MISSING_URL";
    public static final ImagePickerConstants INSTANCE = new ImagePickerConstants();
    public static final String MISSING_ACTIVITY_MESSAGE = "Activity which was provided during module initialization is no longer available";
    public static final String MISSING_URL_MESSAGE = "Intent doesn't contain `url`.";
    public static final String OPTION_ALLOWS_EDITING = "allowsEditing";
    public static final String OPTION_ASPECT = "aspect";
    public static final String OPTION_BASE64 = "base64";
    public static final String OPTION_EXIF = "exif";
    public static final String OPTION_MEDIA_TYPES = "mediaTypes";
    public static final String OPTION_QUALITY = "quality";
    public static final String OPTION_VIDEO_MAX_DURATION = "videoMaxDuration";
    public static final String PENDING_RESULT_EVENT = "ExpoImagePicker.onPendingResult";
    public static final int REQUEST_LAUNCH_CAMERA = 1;
    public static final int REQUEST_LAUNCH_IMAGE_LIBRARY = 2;
    public static final String TAG = "ExponentImagePicker";
    private static final String[][] exifTags;

    static {
        String[][] strArr = new String[TsExtractor.TS_STREAM_TYPE_AC3][];
        strArr[0] = new String[]{"string", ExifInterface.TAG_ARTIST};
        strArr[1] = new String[]{"int", ExifInterface.TAG_BITS_PER_SAMPLE};
        strArr[2] = new String[]{"int", ExifInterface.TAG_COMPRESSION};
        strArr[3] = new String[]{"string", ExifInterface.TAG_COPYRIGHT};
        strArr[4] = new String[]{"string", ExifInterface.TAG_DATETIME};
        strArr[5] = new String[]{"string", ExifInterface.TAG_IMAGE_DESCRIPTION};
        strArr[6] = new String[]{"int", ExifInterface.TAG_IMAGE_LENGTH};
        strArr[7] = new String[]{"int", ExifInterface.TAG_IMAGE_WIDTH};
        strArr[8] = new String[]{"int", ExifInterface.TAG_JPEG_INTERCHANGE_FORMAT};
        strArr[9] = new String[]{"int", ExifInterface.TAG_JPEG_INTERCHANGE_FORMAT_LENGTH};
        strArr[10] = new String[]{"string", ExifInterface.TAG_MAKE};
        strArr[11] = new String[]{"string", ExifInterface.TAG_MODEL};
        strArr[12] = new String[]{"int", ExifInterface.TAG_ORIENTATION};
        strArr[13] = new String[]{"int", ExifInterface.TAG_PHOTOMETRIC_INTERPRETATION};
        strArr[14] = new String[]{"int", ExifInterface.TAG_PLANAR_CONFIGURATION};
        strArr[15] = new String[]{"double", ExifInterface.TAG_PRIMARY_CHROMATICITIES};
        strArr[16] = new String[]{"double", ExifInterface.TAG_REFERENCE_BLACK_WHITE};
        strArr[17] = new String[]{"int", ExifInterface.TAG_RESOLUTION_UNIT};
        strArr[18] = new String[]{"int", ExifInterface.TAG_ROWS_PER_STRIP};
        strArr[19] = new String[]{"int", ExifInterface.TAG_SAMPLES_PER_PIXEL};
        strArr[20] = new String[]{"string", ExifInterface.TAG_SOFTWARE};
        strArr[21] = new String[]{"int", ExifInterface.TAG_STRIP_BYTE_COUNTS};
        strArr[22] = new String[]{"int", ExifInterface.TAG_STRIP_OFFSETS};
        strArr[23] = new String[]{"int", ExifInterface.TAG_TRANSFER_FUNCTION};
        strArr[24] = new String[]{"double", ExifInterface.TAG_WHITE_POINT};
        strArr[25] = new String[]{"double", ExifInterface.TAG_X_RESOLUTION};
        strArr[26] = new String[]{"double", ExifInterface.TAG_Y_CB_CR_COEFFICIENTS};
        strArr[27] = new String[]{"int", ExifInterface.TAG_Y_CB_CR_POSITIONING};
        strArr[28] = new String[]{"int", ExifInterface.TAG_Y_CB_CR_SUB_SAMPLING};
        strArr[29] = new String[]{"double", ExifInterface.TAG_Y_RESOLUTION};
        strArr[30] = new String[]{"double", ExifInterface.TAG_APERTURE_VALUE};
        strArr[31] = new String[]{"double", ExifInterface.TAG_BRIGHTNESS_VALUE};
        strArr[32] = new String[]{"string", ExifInterface.TAG_CFA_PATTERN};
        strArr[33] = new String[]{"int", ExifInterface.TAG_COLOR_SPACE};
        strArr[34] = new String[]{"string", ExifInterface.TAG_COMPONENTS_CONFIGURATION};
        strArr[35] = new String[]{"double", ExifInterface.TAG_COMPRESSED_BITS_PER_PIXEL};
        strArr[36] = new String[]{"int", ExifInterface.TAG_CONTRAST};
        strArr[37] = new String[]{"int", ExifInterface.TAG_CUSTOM_RENDERED};
        strArr[38] = new String[]{"string", ExifInterface.TAG_DATETIME_DIGITIZED};
        strArr[39] = new String[]{"string", ExifInterface.TAG_DATETIME_ORIGINAL};
        strArr[40] = new String[]{"string", ExifInterface.TAG_DEVICE_SETTING_DESCRIPTION};
        strArr[41] = new String[]{"double", ExifInterface.TAG_DIGITAL_ZOOM_RATIO};
        strArr[42] = new String[]{"string", ExifInterface.TAG_EXIF_VERSION};
        strArr[43] = new String[]{"double", ExifInterface.TAG_EXPOSURE_BIAS_VALUE};
        strArr[44] = new String[]{"double", ExifInterface.TAG_EXPOSURE_INDEX};
        strArr[45] = new String[]{"int", ExifInterface.TAG_EXPOSURE_MODE};
        strArr[46] = new String[]{"int", ExifInterface.TAG_EXPOSURE_PROGRAM};
        strArr[47] = new String[]{"double", ExifInterface.TAG_EXPOSURE_TIME};
        strArr[48] = new String[]{"double", ExifInterface.TAG_F_NUMBER};
        strArr[49] = new String[]{"string", ExifInterface.TAG_FILE_SOURCE};
        strArr[50] = new String[]{"int", ExifInterface.TAG_FLASH};
        strArr[51] = new String[]{"double", ExifInterface.TAG_FLASH_ENERGY};
        strArr[52] = new String[]{"string", ExifInterface.TAG_FLASHPIX_VERSION};
        strArr[53] = new String[]{"double", ExifInterface.TAG_FOCAL_LENGTH};
        strArr[54] = new String[]{"int", ExifInterface.TAG_FOCAL_LENGTH_IN_35MM_FILM};
        strArr[55] = new String[]{"int", ExifInterface.TAG_FOCAL_PLANE_RESOLUTION_UNIT};
        strArr[56] = new String[]{"double", ExifInterface.TAG_FOCAL_PLANE_X_RESOLUTION};
        strArr[57] = new String[]{"double", ExifInterface.TAG_FOCAL_PLANE_Y_RESOLUTION};
        strArr[58] = new String[]{"int", ExifInterface.TAG_GAIN_CONTROL};
        strArr[59] = new String[]{"int", ExifInterface.TAG_ISO_SPEED_RATINGS};
        strArr[60] = new String[]{"string", ExifInterface.TAG_IMAGE_UNIQUE_ID};
        strArr[61] = new String[]{"int", ExifInterface.TAG_LIGHT_SOURCE};
        strArr[62] = new String[]{"string", ExifInterface.TAG_MAKER_NOTE};
        strArr[63] = new String[]{"double", ExifInterface.TAG_MAX_APERTURE_VALUE};
        strArr[64] = new String[]{"int", ExifInterface.TAG_METERING_MODE};
        strArr[65] = new String[]{"int", ExifInterface.TAG_NEW_SUBFILE_TYPE};
        strArr[66] = new String[]{"string", ExifInterface.TAG_OECF};
        strArr[67] = new String[]{"int", ExifInterface.TAG_PIXEL_X_DIMENSION};
        strArr[68] = new String[]{"int", ExifInterface.TAG_PIXEL_Y_DIMENSION};
        strArr[69] = new String[]{"string", ExifInterface.TAG_RELATED_SOUND_FILE};
        strArr[70] = new String[]{"int", ExifInterface.TAG_SATURATION};
        strArr[71] = new String[]{"int", ExifInterface.TAG_SCENE_CAPTURE_TYPE};
        strArr[72] = new String[]{"string", ExifInterface.TAG_SCENE_TYPE};
        strArr[73] = new String[]{"int", ExifInterface.TAG_SENSING_METHOD};
        strArr[74] = new String[]{"int", ExifInterface.TAG_SHARPNESS};
        strArr[75] = new String[]{"double", ExifInterface.TAG_SHUTTER_SPEED_VALUE};
        strArr[76] = new String[]{"string", ExifInterface.TAG_SPATIAL_FREQUENCY_RESPONSE};
        strArr[77] = new String[]{"string", ExifInterface.TAG_SPECTRAL_SENSITIVITY};
        strArr[78] = new String[]{"int", ExifInterface.TAG_SUBFILE_TYPE};
        strArr[79] = new String[]{"string", ExifInterface.TAG_SUBSEC_TIME};
        strArr[80] = new String[]{"string", ExifInterface.TAG_SUBSEC_TIME_DIGITIZED};
        strArr[81] = new String[]{"string", ExifInterface.TAG_SUBSEC_TIME_ORIGINAL};
        strArr[82] = new String[]{"int", ExifInterface.TAG_SUBJECT_AREA};
        strArr[83] = new String[]{"double", ExifInterface.TAG_SUBJECT_DISTANCE};
        strArr[84] = new String[]{"int", ExifInterface.TAG_SUBJECT_DISTANCE_RANGE};
        strArr[85] = new String[]{"int", ExifInterface.TAG_SUBJECT_LOCATION};
        strArr[86] = new String[]{"string", ExifInterface.TAG_USER_COMMENT};
        strArr[87] = new String[]{"int", ExifInterface.TAG_WHITE_BALANCE};
        strArr[88] = new String[]{"int", ExifInterface.TAG_GPS_ALTITUDE_REF};
        strArr[89] = new String[]{"string", ExifInterface.TAG_GPS_AREA_INFORMATION};
        strArr[90] = new String[]{"double", ExifInterface.TAG_GPS_DOP};
        strArr[91] = new String[]{"string", ExifInterface.TAG_GPS_DATESTAMP};
        strArr[92] = new String[]{"double", ExifInterface.TAG_GPS_DEST_BEARING};
        strArr[93] = new String[]{"string", ExifInterface.TAG_GPS_DEST_BEARING_REF};
        strArr[94] = new String[]{"double", ExifInterface.TAG_GPS_DEST_DISTANCE};
        strArr[95] = new String[]{"string", ExifInterface.TAG_GPS_DEST_DISTANCE_REF};
        strArr[96] = new String[]{"double", ExifInterface.TAG_GPS_DEST_LATITUDE};
        strArr[97] = new String[]{"string", ExifInterface.TAG_GPS_DEST_LATITUDE_REF};
        strArr[98] = new String[]{"double", ExifInterface.TAG_GPS_DEST_LONGITUDE};
        strArr[99] = new String[]{"string", ExifInterface.TAG_GPS_DEST_LONGITUDE_REF};
        strArr[100] = new String[]{"int", ExifInterface.TAG_GPS_DIFFERENTIAL};
        strArr[101] = new String[]{"double", ExifInterface.TAG_GPS_IMG_DIRECTION};
        strArr[102] = new String[]{"string", ExifInterface.TAG_GPS_IMG_DIRECTION_REF};
        strArr[103] = new String[]{"string", ExifInterface.TAG_GPS_LATITUDE_REF};
        strArr[104] = new String[]{"string", ExifInterface.TAG_GPS_LONGITUDE_REF};
        strArr[105] = new String[]{"string", ExifInterface.TAG_GPS_MAP_DATUM};
        strArr[106] = new String[]{"string", ExifInterface.TAG_GPS_MEASURE_MODE};
        strArr[107] = new String[]{"string", ExifInterface.TAG_GPS_PROCESSING_METHOD};
        strArr[108] = new String[]{"string", ExifInterface.TAG_GPS_SATELLITES};
        strArr[109] = new String[]{"double", ExifInterface.TAG_GPS_SPEED};
        strArr[110] = new String[]{"string", ExifInterface.TAG_GPS_SPEED_REF};
        strArr[111] = new String[]{"string", ExifInterface.TAG_GPS_STATUS};
        strArr[112] = new String[]{"string", ExifInterface.TAG_GPS_TIMESTAMP};
        strArr[113] = new String[]{"double", ExifInterface.TAG_GPS_TRACK};
        strArr[114] = new String[]{"string", ExifInterface.TAG_GPS_TRACK_REF};
        strArr[115] = new String[]{"string", ExifInterface.TAG_GPS_VERSION_ID};
        strArr[116] = new String[]{"string", ExifInterface.TAG_INTEROPERABILITY_INDEX};
        strArr[117] = new String[]{"int", ExifInterface.TAG_THUMBNAIL_IMAGE_LENGTH};
        strArr[118] = new String[]{"int", ExifInterface.TAG_THUMBNAIL_IMAGE_WIDTH};
        strArr[119] = new String[]{"int", ExifInterface.TAG_DNG_VERSION};
        strArr[120] = new String[]{"int", ExifInterface.TAG_DEFAULT_CROP_SIZE};
        strArr[121] = new String[]{"int", ExifInterface.TAG_ORF_PREVIEW_IMAGE_START};
        strArr[122] = new String[]{"int", ExifInterface.TAG_ORF_PREVIEW_IMAGE_LENGTH};
        strArr[123] = new String[]{"int", ExifInterface.TAG_ORF_ASPECT_FRAME};
        strArr[124] = new String[]{"int", ExifInterface.TAG_RW2_SENSOR_BOTTOM_BORDER};
        strArr[125] = new String[]{"int", ExifInterface.TAG_RW2_SENSOR_LEFT_BORDER};
        strArr[126] = new String[]{"int", ExifInterface.TAG_RW2_SENSOR_RIGHT_BORDER};
        strArr[127] = new String[]{"int", ExifInterface.TAG_RW2_SENSOR_TOP_BORDER};
        strArr[128] = new String[]{"int", ExifInterface.TAG_RW2_ISO};
        exifTags = strArr;
    }

    private ImagePickerConstants() {
    }

    public final String[][] getExifTags() {
        return exifTags;
    }
}
